### PR TITLE
fix: retrieve price type

### PR DESCRIPTION
**Pull request by shahednasser**

### CODE REVIEW

**Review by sradevski — APPROVED** [review]

**Comment by sradevski** [comment]
@shahednasser it seems the build is failing, can you just check that first please?

**Comment by shahednasser** [comment]
@sradevski seems like the latest changes in the http types have messed up a lot of things. I've tried resolving these type errors with what made sense to me, but as I'm not very familiar with this project would be great if you gave these changes a good look

**Comment by sradevski** [comment]
Looks good 👍

**Comment by shahednasser** [comment]
@sradevski  Any idea why the test fails with `[Error]: Fields [+category_children] are not valid`? I can't reproduce it

**Comment by sradevski** [comment]
@shahednasser please ignore the tests for now, as long as `storefront-v2-staging` is passing we're good. We'll get to the tests once the API stabilizes a bit more

**Pull request merged**
